# Model arguments
model_name_or_path: Qwen/Qwen3-4B
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: friendshipkim/RUCAIBox-Story-Generation-test
dataset_prompt_column: prompt
dataset_train_split: train
dataset_test_split: test
system_prompt: ""
# system_prompt: "You are a helpful AI Assistant that provides well-reasoned and detailed responses. You first think about the reasoning process as an internal monologue and then provide the user with the answer. Respond in the following format: <think>\n...\n</think>\n<answer>\n...\n</answer>"

# GRPO trainer config
bf16: true
use_vllm: false
do_eval: false
# vllm_gpu_memory_utilization: 0.7
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
# hub_model_id: Qwen3-1.7B-ultrachat-GRPO
# hub_strategy: every_save
learning_rate: 2.0e-06
log_completions: true
log_level: info
logging_first_step: true
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 512
max_completion_length: 2048
max_steps: 100
num_generations: 8
num_train_epochs: 5
output_dir: saved_models/Qwen3-4B-sg-bsz64-ranking-ts100-skywork8b-seed42-lr2e-6-2gpus
run_name: Qwen3-4B-sg-bsz64-ranking-ts100-skywork8b-seed42-lr2e-6-2gpus
overwrite_output_dir: true
per_device_eval_batch_size: 32
per_device_train_batch_size: 32 
generation_batch_size: 512 
push_to_hub: false
report_to:
- wandb
reward_funcs:
- skywork-qwen3-8b
reward_weights:
- 1.0
save_strategy: "steps"
save_steps: 25
save_total_limit: 10
seed: 42
warmup_ratio: 0.1
advantage: "ranking"
token_broadcast: "uniform"